server:
  port: 8081
  servlet:
    encoding:
      charset: UTF-8
  compression:
    enabled: true
    min-response-size: 1024
# DataSource Config
# 多数据源
spring:
  profiles:
    active: sit
  redis:
    jedis:
      pool:
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接 默认也是0
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
  #spring的aop默认使用jdk动态代理模式，此处开启cglib动态代理
  #假若我们想要代理的对象并没有实现任何接口，这时候我们就要用到CGLIB动态代理了，
  #这就是它与JDK动态代理主要不同的地方。
  aop:
    proxy-target-class: true
swagger:
  enable: true
  api-description:
    title: swagger 文档说明
    description: 不知道怎么描述
encrypt:
  config:
    enable: true  #key: #密钥应该在启动时放在参数里，或者放在env里
    prefix: TT(
    suffix: )
    version: 1.0
    key: 9armor0safe4dog1
demo: TT(nGkRyFhFQoicg4xtPtF5ag==)

